version: "3"
services:
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data

  mining_portal:
    build: ./node-open-mining-portal
    ports:
      - "17117:17117" # nomp cli
      - "80:80" # web interface
      - "3333:3333" # sha256 pool
    volumes:
      - ./configs/config.js:/code/config.js
      - ./configs/pool_configs:/code/pool_configs
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - redis

volumes:
  redis-data:
